# Project metadata for linting support.
# The packages listed here support linting commands.
# They come from mathlib's tooling.
[lint]
packages = [
  "leanprover-community/mathlib",
  "leanprover-community/proofwidgets",
  "leanprover-community/aesop",
  "leanprover-community/Qq",
  "leanprover-community/import-graph",
  "leanprover-community/LeanSearchClient",
  "leanprover-community/plausible",
  "leanprover-community/batteries",
  "leanprover/lean4-cli"
]
